---

services:
  xui:
    image: alireza7/x-ui
    container_name: x-ui
    hostname: hileud
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx-x-ui
    network_mode: host
    volumes:
    - $PWD/nginx.conf:/etc/nginx/nginx.conf
    - $PWD/xray.conf:/etc/nginx/conf.d/xray.conf
    - $PWD/cert/:/etc/nginx/ssl
    restart: unless-stopped
