---

services:
  xui:
    image: alireza7/x-ui
    container_name: x-ui
    hostname: hileud
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
    
  haproxy:
    image: haproxy:2.8
    container_name: haproxy-xray
    network_mode: host
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./cert/xray.pem:/usr/local/etc/haproxy/certs/xray.pem:ro
    restart: unless-stopped
